### ISSUE TITLE
Search for Special Characters (like Tab) doesn't work

### ISSUE THREAD

**Issue by mhellmeier** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#10]
I want to replace all tabs (ASCII char 9 / Unicode U+0009) in all files with four empty spaces ("    "). When searching for the tab character, the plugin doesn't find any results. When using the built-in Obsidian search, it is able to find and replace it per file. Therefore, there is a bug with special characters (like tabs) that the plugin can't find.

**Comment by MahmoudFawzyKhalil** [comment]
This should work now if you use regexmode and use `\t` for tab.
![image](https://github.com/MahmoudFawzyKhalil/obsidian-global-search-and-replace/assets/73137611/ff2dffd7-be05-4447-9ccb-318f3c2b01bd)
