### ISSUE TITLE
One click global replacement

### ISSUE THREAD

**Issue by Yunmoyan** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#12]
Hello, is there a chance to add a global one-click replace all feature? I believe it would be meaningful.Thank you very much.

**Comment by MahmoudFawzyKhalil** [comment]
Hello, this is a duplicate of #5 so I will close it here.

Thank you for your suggestion.

**Comment by Yunmoyan** [comment]
I have already understood, thanks for your response.
