### ISSUE TITLE
[FEATURE REQUEST] Option to make the search case sensitive

### ISSUE THREAD

**Issue by DutchPete** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#2]
This option would be really useful too as in some cases it can narrow down the output list considerable.

**Comment by MahmoudFawzyKhalil** [comment]
Currently, the search is case **sensitive** by default, with the option to make that toggle-able being one of the features I want to implement soon.

So this is definitely a feature that is in the pipeline.

**Comment by DutchPete** [comment]
OK, thank you.
