### ISSUE TITLE
[FR] Regex support

### ISSUE THREAD

**Issue by a13ph** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#3]
Regular expression find-and-replace across vault would be really handy and would alleviate the need to open vault in vscode or similar code editors.

**Comment by MahmoudFawzyKhalil** [comment]
Yes, this is definitely a feature that will be implemented soon. Right now I am just focusing on getting the plugin accepted into the official obsidian repository so that it is easier to download.

**Comment by ichmoimeyo** [comment]
> Yes, this is definitely a feature that will be implemented soon. 

Great news, thanks.

**Comment by spiritualgeek** [comment]
Still not implemented, and unfortunately the plugin is fairly useless without it
