### ISSUE TITLE
New command for global YAML replacing

### ISSUE THREAD

**Issue by imed-ghomari** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#6]
Hi, I don't know if this is within the scope of the plugin, but I've always wanted to replace multiple YAML values in all my vault. And this plugin seems to do something similar. I was wondering if another command could be added to target YAML only values. Thank you very much.

**Comment by MahmoudFawzyKhalil** [comment]
By YAML, do you mean the frontmatter in each note?
```markdown
---
key: value
---

*rest of note*
```

**Comment by imed-ghomari** [comment]
yes

**Comment by MahmoudFawzyKhalil** [comment]
I think this is hopefully quite possible to implement as the Obsidian API provides access to the frontmatter for each note. I will add it to the feature list. Thanks for your suggestion.

**Comment by LuiZzz-Menezes** [comment]
I need that too. I want to change a tag of some notes that its in frontmatter

**Comment by Jack-KkKk** [comment]
I need this feature as well. I would really appreciate it if you could add it.

**Comment by imed-ghomari** [comment]
This has been implemented here https://github.com/fez-github/obsidian-multi-properties/issues/2

**Comment by MahmoudFawzyKhalil** [comment]
Thank you @imeed166
