### ISSUE TITLE
Not picking up any files

### ISSUE THREAD

**Issue by aikruger** [MahmoudFawzyKhalil/obsidian-global-search-and-replace#9]
For some reason I cannot get it to pick up any files. Can't seem to find any additional instructions.

**Comment by MahmoudFawzyKhalil** [comment]
The plugin only searches in .md files in your current vault. Are you sure both of those conditions match?

**Comment by aikruger** [comment]
yes both conditions are matched. I first installed through BRAT could that make a difference?

**Comment by MahmoudFawzyKhalil** [comment]
I am not sure if first installing through BRAT could make a difference. Can you try it on a fresh vault with no other plugins installed?

**Comment by muteboy** [comment]
Hi, rather than create new issue I thought I'd add to this. I've uninstalled and reinstalled from the plugins page. I enter text to search, and nothing happens. My vault is quite large: over 4000 small notes, all in MD format.
What could be the problem?
